In [24]:
import os
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix # check how accurate

#### Prereq

Example cancer test

99% positive, then cancer
10% false positive
5% of the population have cancer

Give `P(cancer | positive)`

In [25]:
TRAIN = '../data/lec_6/Example1_train.xlsx'
TEST = '../data/lec_6/Example1_test.xlsx'
train = pd.ExcelFile(TRAIN)
test = pd.ExcelFile(TEST)

In [26]:
X_train = train.parse('Features')
y_train = train.parse('target')

X_test = test.parse('Features')
y_test = test.parse('target')

In [27]:
clf = GaussianNB().fit(X_train, y_train)

/Users/ninz/.local/share/virtualenvs/cs297-fZk1rqQo/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [28]:
y_pre = clf.predict(X_test)

In [36]:
print(X_test)
print('Accuracy:', clf.score(X_test, y_test))
print('Confussion Matrix:', confusion_matrix(y_test, y_pre))
print('Probability', clf.predict_proba(X_test))

   Height (in.)  Weight (lbs.)
0           143             69
1           187             69
2           186             64
3           165             66
4           197             70
5           155             67
6           134             66
Accuracy: 1.0
Confussion Matrix: [[4 0]
 [0 3]]
Probability [[9.99998351e-01 1.64869490e-06]
 [2.51731644e-05 9.99974827e-01]
 [9.13363581e-05 9.99908664e-01]
 [7.88858286e-01 2.11141714e-01]
 [1.65171977e-07 9.99999835e-01]
 [9.98747152e-01 1.25284785e-03]
 [9.99999994e-01 5.64599397e-09]]


### HOMEWORK

Do the same thing for the iris data set, split the test

test_size = 0.3, random_state = 1

In [37]:
# This is how we split training data
iris = datasets.load_iris()
X_iris = iris.data
y_iris = iris.target

X_train, X_test, y_train, y_test = train_test_split(X_iris, y_iris, test_size=0.3, random_state=1)

In [40]:
clf_iris = GaussianNB().fit(X_train, y_train)
y_pre = clf_iris.predict(X_test)

In [42]:
print('Accuracy:', clf_iris.score(X_test, y_test))
print('Confussion Matrix:', confusion_matrix(y_test, y_pre))
print('Probability', clf_iris.predict_proba(X_test))

Accuracy: 0.9333333333333333
Confussion Matrix: [[14  0  0]
 [ 0 16  2]
 [ 0  1 12]]
Probability [[1.00000000e+000 7.30172724e-017 1.92698897e-023]
 [1.83127445e-031 9.99999349e-001 6.50949259e-007]
 [6.64026638e-099 9.71309470e-001 2.86905301e-002]
 [1.00000000e+000 4.50426332e-015 5.93894621e-022]
 [1.24729705e-266 1.50022255e-009 9.99999998e-001]
 [1.25848413e-120 4.97361143e-001 5.02638857e-001]
 [8.22548006e-192 6.90370263e-007 9.99999310e-001]
 [1.00000000e+000 3.05551312e-011 3.69926602e-018]
 [1.00000000e+000 1.34176387e-015 8.87395065e-023]
 [1.55475502e-229 2.00287031e-008 9.99999980e-001]
 [4.44110262e-082 9.99584753e-001 4.15247469e-004]
 [1.00000000e+000 8.14093994e-013 1.12264893e-019]
 [1.14065997e-230 2.17224776e-007 9.99999783e-001]
 [1.44834682e-106 8.84361311e-001 1.15638689e-001]
 [2.27759005e-105 9.66946340e-001 3.30536601e-002]
 [1.00000000e+000 2.98417907e-017 1.87295578e-024]
 [1.26088164e-070 9.99923670e-001 7.63296422e-005]
 [9.89241676e-104 9.75618268e-001 2.