In [1]:
import numpy as np
import pandas as pd

In [45]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, silhouette_score
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn import datasets

In [46]:
from matplotlib import pyplot as plt

In [47]:
df = pd.read_csv('../data/Example1.csv',sep='\t')

km = KMeans(n_clusters=3).fit(df)
pred = km.predict(df)
km.cluster_centers_
km.inertia_

2784.06823408584

In [48]:
pca_df = pd.read_csv('../data/Example3.csv',sep='\t')

pca = PCA(n_components=2).fit(pca_df)
new_x = pca.transform(pca_df)
pca.components_
pca.explained_variance_ratio_

array([0.14890594, 0.13618771])

In [49]:
FILE_X = '../data/lec_4/Example1_features.csv'
FILE_Y = '../data/lec_4/Example1_target.csv'
X = pd.read_csv(FILE_X)
y = pd.read_csv(FILE_Y)

reg = LinearRegression().fit(X, y)
r = reg.score(X, y) # linera correlation score
m = reg.coef_ # coefficient
b = reg.intercept_ # intercept

y_pred = reg.predict(X)


In [66]:
TRAIN = '../data/lec_6/Example1_train.xlsx'
TEST = '../data/lec_6/Example1_test.xlsx'
train = pd.ExcelFile(TRAIN)
test = pd.ExcelFile(TEST)

X_train = train.parse('Features')
y_train = train.parse('target')

X_test = test.parse('Features')
y_test = test.parse('target')

reg = LogisticRegression(random_state=123).fit(X_train, y_train)

reg.score(X_test, y_test) # classifier score

reg.coef_
reg.intercept_

y_pred = reg.predict(X_test)

confusion_matrix(y_test, y_pred) # Confusion matrix for prediction results

reg.predict_proba(X_test) # Probability of where the item belongs. if there are three class, then its 3

/Users/ninz/.local/share/virtualenvs/cs297-fZk1rqQo/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/ninz/.local/share/virtualenvs/cs297-fZk1rqQo/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[0.99575082, 0.00424918],
       [0.02095939, 0.97904061],
       [0.00201855, 0.99798145],
       [0.32386682, 0.67613318],
       [0.00430508, 0.99569492],
       [0.86897212, 0.13102788],
       [0.99703157, 0.00296843]])

In [78]:
FILE_X = '../data/lec_5/kNN_features.csv'
FILE_Y = '../data/lec_5/kNN_target.csv'
X = pd.read_csv(FILE_X)
y_ = pd.read_csv(FILE_Y)

y = y_.Labels

k = KNeighborsClassifier(n_neighbors=3).fit(X, y)
x_new = np.array([[1, -3], [2, 1]])

y_pred = k.predict(x_new)

In [89]:
iris = datasets.load_iris()
X_iris = iris.data
y_iris = iris.target

X_train, X_test, y_train, y_test = train_test_split(X_iris, y_iris, test_size=0.3, random_state=4)

clf = GaussianNB().fit(X_train, y_train)
y_pred = clf.predict(X_test)

clf.score(X_train, y_train)

clf.predict_proba(X_train)

confusion_matrix(y_test, y_pred)

array([[21,  0,  0],
       [ 0, 10,  0],
       [ 0,  1, 13]])